#!/usr/bin/env bash
# filepath: /Users/Dev/Holberton/holbertonschool-network/basics_1/0-change_your_home_IP

# Ajoute ou modifie l'entrée localhost
sudo sed -i.bak '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Ajoute ou modifie l'entrée facebook.com
sudo sed -i.bak '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
